### ISSUE TITLE
rosrun mask_rcnn_ros mask_rcnn_node mistakes

### ISSUE THREAD

**Issue by sunt40** [qixuxiang/mask_rcnn_ros#5]
When I run `rosrun mask_rcnn_ros mask_rcnn_node`
The error as follow:
Traceback (most recent call last):
  File "/home/sunt/catkin_ws/src/mask_rcnn_ros/nodes/mask_rcnn_node", line 15, in <module>
    import visualize
  File "/home/sunt/catkin_ws/src/mask_rcnn_ros/nodes/visualize.py", line 24, in <module>
    sys.path.remove('/opt/ros/indigo/lib/python2.7/dist-packages')
ValueError: list.remove(x): x not in list
I run your code with ROS kinetic , I have modified `sys.path.remove('/opt/ros/indigo/lib/python2.7/dist-packages` to sys.path.remove('/opt/ros/kinetic/lib/python2.7/dist-packages .
What should I do ?

**Comment by punnpkin** [comment]
same problem
